sia:
  score:
    # 每个关键词命中后，有 10 分的基础分
    - "s.equals('品牌词', r.品牌词) ? 40 : 0"
    - "s.equals('竞品词', r.竞品词) ? 30 : 0"
    - "s.equals('英国', seq.get(r, '国家/地区')) ? 10 : 0"
    - "s.equals('美国', seq.get(r, '国家/地区')) ? 10 : 0"
    - "s.equals('澳大利亚', seq.get(r, '国家/地区')) ? 5 : 0"
    - "s.equals('法国', seq.get(r, '国家/地区')) ? 5 : 0"
    - "s.equals('加拿大', seq.get(r, '国家/地区')) ? 5 : 0"
    - "s.equals('意大利', seq.get(r, '国家/地区')) ? 5 : 0"
    - "s.equals('韩国', seq.get(r, '国家/地区')) ? 5 : 0"
    - "s.equals('新加坡', seq.get(r, '国家/地区')) ? 5 : 0"
    - "r.专业 != nil && !s.equals('影视动画类', r.专业) ? 10 : 0"
    - "s.equals('艺术', r.院校) || s.equals('音乐', r.院校) ? 10 : 0"
    - "r.行业词 != nil ? 10 : 0"
    - "seq.get(r, '学校/大学') != nil ? -5 : 0"
    - "r.费用 != nil ? -5 : 0"
    - "r.申请条件 != nil ? -5 : 0"
    - "r.排名 != nil ? -5 : 0"
    - "r.疑问 != nil ? -5 : 0"
  keyword-group:
    "国家/地区":
      "英国": [英国,伦敦,aa建筑,建筑联盟,皇家艺术学院,中央圣马丁,伯明翰.AA联盟,爱丁堡,切尔西]
      "美国": [美国,纽约,parsons,pratt,旧金山艺术大学,罗德岛设计学院,帕森斯设计学院,芝加哥,伯克利,加利福尼亚,加州大学伯克利,加州,旧金山,洛杉矶,波士顿,马里兰,伊利诺伊,密西根]
      "日本": [日本]
      "法国": [法国,巴黎,esmod]
      "澳洲": [澳大利亚,澳洲,墨尔本,新西兰]
      "德国": [德国,柏林]
      "加拿大": [加拿大,温哥华]
      "俄罗斯": [俄罗斯]
      "意大利": [意大利,佛罗伦萨,米兰]
      "新加坡": [新加坡]
      "荷兰": [荷兰]
      "韩国": [韩国]
      "香港": [香港]
      "澳门": [澳门]
      "欧洲": [欧洲,北欧]
      "爱尔兰": [爱尔兰]
      "丹麦": [丹麦]
    "专业":
      "影视动画类": [动画,摄影,电影,游戏]
      "艺术人文类": [艺术管理,插画,纯艺术,艺术策展,艺术史]
      "时尚类": [戏服,服装,珠宝,时尚管理,面料,时尚造型与传播]
      "视觉类": [平面,数字媒体,视觉传达]
      "工业交互类": [交互,工业,交通工具,家具,产品设计,服务设计]
      "空间类": [舞美,景观,室内设计,建筑,城市设计]
      "其他专业": [美术,编导,城市规划,影视,园林,雕塑,版画,油画,动漫,纯艺,绘画,艺术设计,设计,艺术,多媒体,纺织品,广告,环境设计,戏剧,陶艺,时装,室内,首饰,数字艺术,展示]
    "院校":
      "综合": [德雷塞尔大学,加州大学洛杉矶分校,剑桥大学,南安普顿大学,纽卡斯尔大学,提赛德大学,谢菲尔德大学,英国约克大学,米兰理工大学,中央兰开夏大学,诺丁汉大学,伦敦大学城市学院,阿德莱德大学,巴斯斯巴大学,班戈大学,格拉斯哥大学,墨尔本大学,悉尼科技大学,皇家墨尔本理工大学,西澳大学,澳大利亚国立大学,科廷大学,悉尼大学,新南威尔士大学,香港大学,香港浸会大学,香港理工大学,莫纳什大学,卡迪夫大学,伯明翰城市大学,莱斯大学,田纳西大学诺克斯维尔分校,查普曼大学,密歇根大学,纽约城市大学亨特学院,乔治布朗学院,圣路易斯华盛顿大学,爱丁堡龙比亚大学,辛辛那提大学,波士顿大学,西门菲莎大学,谢菲尔德哈勒姆大学,伦敦大学金史密斯学院,赫特福德大学,新墨西哥大学,加州大学圣地亚哥分校,伦敦大学学院,爱丁堡大学,利兹大学,拉夫堡大学,圣安德鲁斯大学,威斯康星大学麦迪逊分校,纽约大学,弗吉尼亚联邦大学,俄亥俄州立大学,伊利诺伊大学厄巴纳香槟分校,宾夕法尼亚大学,罗彻斯特理工学院,伦敦大学玛丽皇后学院,巴德学院,天普大学,阿尔弗雷德大学,巴斯大学,耶鲁大学,牛津大学,哈佛大学,哥伦比亚大学,考文垂大学,卡内基梅隆大学,雪城大学,巴纳德学院,康奈尔大学,金斯顿大学,肯特州立大学,布鲁内尔大学,南加州大学,筑波大学,日本大学,长冈造形大学,柏林工业大学,东京大学,高布兰学院,京都大学,旧金山大学,曼彻斯特大学,萨里大学,约克圣约翰大学,爱尔兰国立大学,柏林大学,柏林自由大学,阿伯丁大学,哈德斯菲尔德大学,赫尔大学,斯坦福大学,University of California,阿尔伯塔大学,阿尔伯特学院,阿尔托大学,艾米丽卡尔大学,爱丁堡大学,爱尔兰都柏林大学,弗林德斯大学,昆士兰大学,莫道克大学,维多利亚大学,伍伦贡大学,詹姆斯库克大学,宾夕法尼亚州立大学,滨州州立大学,伯明翰大学,博洛尼亚大学,布兰迪斯大学,布朗大学,布鲁克大学,布里斯托大学,道奇电影学院,成均馆大学,达尔豪斯大学,代尔夫特理工大学,科堡应用技术与艺术大学,乌尔姆设计学院,亚琛工业大学,德累斯顿大学,东安格利亚大学,东伦敦大学,东英吉利大学,杜伦大学,多伦多大学,俄州州立大学,法尔茅斯大学,高等商学院,梅斯大学,范德堡大学,芬兰大学,佛罗里达国际大学,佛罗里达州立大学,哥伦比亚艺术学院,格拉摩根大学,弘益大学,华盛顿州立大学,华盛顿圣路易斯大学,华威大学,惠特曼学院,加利福尼亚路德大学,加利福尼亚艺术学院,阿尔伯塔学院,百年理工学院,达尔豪斯大学,道格拉斯学院,多伦多大学,湖首大学,滑铁卢大学,卡普顿大学,劳伦森大学,伦敦国际学院,克马斯特大学,麦吉尔大学,曼尼托巴大学,纽芬兰纪念大学,温哥华大学,渥太华大学,西蒙菲莎大学,西蒙弗雷泽大学,西三一大学,约克大学,加州大学,欧文大学,卡内基梅陇大学,卡内基美隆大学,芝加哥大学,德保罗大学,约翰霍普金斯大学,西伦敦大学,桑德兰大学,朴茨茅斯大学,帝国理工大学,伦敦大学,伦敦城市大学,利物浦大学,雷丁大学,兰卡斯特大学,莱斯特大学,拉夫堡大学,考文垂,印度理工学院,印第安纳大学,essex大学,leicester大学,梅努斯大学,奥斯陆国家艺术学院,爱荷华大学,奥克兰大学,安格利亚鲁斯金大学,昆士兰科技大学,堪培拉大学,澳大利亚科技大学,亚格里菲斯大学,迪肯大学,澳大利亚联邦大学,麦考瑞大学,蒙纳士大学,南澳大学,南十字星大学,托伦斯大学,维多利亚艺术学院,卧龙岗大学,澳洲国立大学,澳洲大学,皇家理工大学,索邦大学,巴纳德女子学院,洪堡大学,北安普顿大学,北德克萨斯州大学,北海道大学,南特大西洋设计学院,早稻田大学,苏塞克斯大学,斯旺西大学,曼哈顿大学,伦敦玛丽女王,伦敦国王,龙比亚大学,约翰摩尔大学,皇家理工学院,红砖大学,格林威治大学,邓迪大学,德蒙福特大学,埃克塞特大学,奥斯特大学,brunel大学,伊利诺伊香槟分校,雪尔顿学院,休斯顿大学,锡拉丘兹大学,西英格兰大学,西澳大利亚大学,坦普尔大学,图尔大学,斯特莱斯克莱德大学,坦普尔大学,苏塞克斯大学,圣地亚哥大学,圣路易斯大学,圣三一学院,萨利大学,普渡大学,乔治城大学,匹兹堡大学,纽约州立大学,诺瓦艺术,石溪大学,南加利福尼亚大学,密苏里大学,密歇根州立大学,明尼苏达大学,皇家理工大学,米兰理工,佐治亚大学,佐治亚理工学院,美利坚大学,中田纳西州立大学,美国州立大学,犹他州立大学,印第安纳波利斯大学,伊利诺理工大学,新奥尔良大学,西俄勒冈大学,威斯康星,特拉华州立大学,特洛伊大学,特拉华州立大学,太平洋大学,塔夫茨大学,University of Southern California,uscd,伯恩茅斯大学,丹麦大学,赫尔辛基大学,加利福尼亚大学,科罗拉多大学,肯特大学,拉筹伯大学,莱姆顿学院,劳里埃大学,劳瑞尔大学,利兹贝克特大学,马里兰大学,阿什兰大学,埃默里大学,阿肯色州立大学,阿卡迪亚大学,爱荷华州立大学,奥本大学,奥斯汀大学,北德克萨斯大学,北卡大学,北亚利桑那大学,北伊利诺伊大学,贝佛大学,贝翰文大学,本特利大学,博林格林州立大学,布莱恩特大学,布里奇波特大学,常青藤大学,戴顿大学,戴维斯大学,德克萨斯理工大学,德克萨斯州大学,德州大学,加利福尼亚大学,底特律大学,杜兰大学,俄亥俄大学,俄亥俄州大学,佛罗里达理工大学,俄勒冈大学,佛罗里达大学,福特汉姆大学,哈町大学,华盛顿大学,加利福尼亚大学,加州浸会大学,加州社区大学,加州州立大学,旧金山州立大学,卡耐基大学,卡普兰大学,凯斯西储大学,凯泽大学,堪萨斯大学,康涅狄格大学,科罗拉多大学,克拉克大学,克莱姆森大学,肯恩大学,库克大学,里海大学,林肯大学,罗格斯大学,罗切斯特大学,洛杉矶大学,马里兰大学,马歇尔大学,迈阿密大学,麦迪逊大学,米勒斯维尔大学,密苏里州立大学,密西根大学,密西西比大学,安娜堡大学,莫瑞州立大学,南佛罗里达大学,南伊利诺伊大学,犹他大学,巴鲁学院,纽约理工大学,纽约城市大学,纽约理工学院,圣约翰大学,纽约州大学,库克大学,罗切斯特大学，诺斯伍德大学,佩丁大学,佩珀代因大学,佩斯大学,普度大学,普林斯顿大学,华盛顿大学,乔治梅森大学,乔治亚,桥港大学,塞勒姆州立大学,社区大学,圣地亚哥州立大学,圣迭戈大学,圣克劳德州立大学,索菲亚大学,陶森大学,特拉华大学,托莱多大学,瓦尔帕莱索大学,威斯康辛,新泽西理工大学,新泽西州立大学,罗格斯大学,亚利桑那大学,亚利桑那州立大学,伊利诺伊大学,伊利诺伊理工大学,佐治亚州立大学,蒙特克莱尔州立大学,密苏里州立大学,墨尔本皇家理工,纽布伦斯威克大学,巴鲁学院,纽约市立大学,沃罗涅日国立大学,亚利桑那州立大学,伊利诺伊大学,伯恩茅斯大学,国王学院,南威尔士大学,维吉尼亚联邦大学,西亚斯国际学院,伊利诺伊州香槟分校,密西根州立大学,罗切斯特理工,加利福尼亚州大学,加州理工大学,皇后大学,科克大学]
      "艺术": [柏林艺术大学,伦敦电影学院,纽约室内设计学院,罗马美术学院,米兰布雷拉美术学院,米兰新美术学院,南加州建筑学院,威尼斯美术学院,都灵美术学院,温哥华电影学院,安大略艺术设计学院,新斯科舍艺术与设计大学,圣荷西大学艺术与设计学院,瑞玲艺术设计学院,克利夫兰艺术学院,库伯联盟学院,加州艺术大学,伦敦大学学院斯莱德美术学院,奥斯陆国立艺术学院,英国伦敦皇家美术学院,列宾美术学院,巴黎国立高等美术学院,佛罗伦萨国立美术学院,谢尔丹学院,lisaa巴黎高等应用艺术学院,麻省艺术设计学院,波士顿建筑学院,格拉斯哥艺术学院,伯恩茅斯艺术大学,诺丁汉特伦特大学,克兰布鲁克艺术学院,伦敦传媒学院,旧金山艺术大学,明尼阿波利斯艺术设计学院,建筑联盟学院,温布尔登艺术学院,美国时尚设计商业学院,柏丽慕达时装学院,奥蒂斯艺术与设计学院,美国电影学院,创意艺术大学,爱丁堡艺术学院,欧纳菲珠宝设计学院,加州艺术学院,诺瓦艺术与设计大学,坎伯韦尔艺术学院,阿尔伯塔艺术设计学院,切尔西艺术学院,安特卫普皇家艺术学院,哥伦布艺术设计学院,纽约时装学院,旧金山艺术学院,艺术中心设计学院,芝加哥艺术学院,马里兰艺术学院,萨凡纳艺术与设计学院,法国高级时装学院,马兰欧尼时装设计学院,伦敦时装学院,普瑞特艺术学院,伦敦艺术大学,皇家艺术学院,罗德岛设计学院,纽约视觉艺术学院,中央圣马丁艺术与设计学院,帕森斯设计学院,东京艺术大学,多摩美术大学,武藏野美术大学,女子美术大学,京都精华大学,德国杜塞尔多夫艺术学院,法国视觉传媒学院,法国艺术文化管理学院,弗罗西诺内美术学院,意大利莱切美术学院,罗马国立美术学院,那不勒斯美术学院,南加州大学电影艺术学院,佩鲁贾美术学院,英国国立电影电视学院,国立阿尔勒摄影学院,布伦艺术学院,巴黎高等文化艺术管理学院,巴黎视觉传达高等艺术学院,巴特莱特建筑学院,柏林媒体设计学院,美国纽约摄影学院,意大利巴勒莫美术学院,中央圣马丁,AA联盟,aa英国建筑学院,aa建筑,ACCD,esmod,纽约时装学院,Parsons,pratt,rca,皇家艺术学院,芝加哥艺术学院,UAL,UCL,ucla,艾米丽卡尔艺术与设计大学,爱丁堡艺术学院,安大略艺术设计学院,安大略艺术设计大学,安特卫普皇家艺术学院,奥地利美术学院,巴黎高等建筑学院,巴黎高等美术学院,巴黎高级时装学院，巴黎国际时装艺术学院，巴黎美术学院，柏丽慕达学院,博洛尼亚美术学院,丹麦艺术学院,奥芬巴赫设计学院,不来梅艺术学院,富克旺根艺术大学,斯图加特造型艺术学院,帝势艺术学院,杜塞尔多夫艺术学院,巴黎美院,巴黎美术学院,高布兰动画学院,里昂艺术戏剧学院,弗罗伦萨美术学院,佛罗伦萨美术学院,格拉斯哥美术学院,格拉斯哥艺术大学,艾米丽卡尔艺术与设计大学,剑桥文理与剑桥艺术,剑桥文理与剑桥艺术,圣马丁,伦敦艺术学院,马兰欧尼,UCA,UCAL,安大略艺术与设计学院,安特卫普皇家美术学院,柏丽慕达学院,柏林白湖艺术学院,佛罗伦萨美院,皇家美术学院,英国AA,布雷拉美术学院,南洋艺术学院,谢尔丹,谢菲尔德,帕森斯,萨凡纳艺术,普瑞特,帕森斯,罗德岛,纽约电影学院,南洋艺术学院,奥蒂斯艺术设计学院,伯恩茅斯艺术学院,伯明翰,旧金山艺术设计学院,卡塞尔艺术学院,伦艺,马兰戈尼,诺瓦设计与艺术大学,欧纳菲设计学院,圣彼得堡艺术学院,苏富比艺术学院,库内奥美术学院,英国建筑联盟,金斯顿艺术学院,梅特电影学院]
      "音乐": [市政厅音乐及戏剧学院,皇家威尔士音乐戏剧学院,伯克利音乐学院,柯蒂斯音乐学院,曼哈顿音乐学院,新英格兰音乐学院,茱莉亚音乐学院,布鲁塞尔皇家音乐学院,格林卡国立音乐学院,汉堡音乐学院,汉诺威音乐和戏剧学院,华沙肖邦音乐大学,皇家北方音乐学院,旧金山音乐学院,利兹音乐学院,伦敦音乐学院,罗马音乐学院,曼海姆音乐学院,帕多瓦音乐学院,帕尔玛音乐学院,塔兰托音乐学院,乌迪内音乐学院,爱丁堡音乐学院,圣三一拉邦音乐舞蹈学院,苏格兰皇家音乐学院,柏林汉斯艾斯勒音乐学院,波士顿音乐学院,博洛尼亚音乐学院,科隆音乐与舞蹈学院,克拉科夫音乐学院,昆士兰音乐学院,莱比锡门德尔松音乐与戏剧学院,里昂国立高等音乐学院,吕贝克音乐学院,马赛国家音乐学院,曼尼斯音乐学院,米兰音乐学院,挪威音乐学院,阿维利诺音乐学院,亚历山德里亚音乐学院,悉尼音乐学院,魏玛李斯特音乐学院,维也纳音乐学院,维尔茨堡音乐学院,圣彼得堡音乐学院,帕尔马音乐学院,都灵音乐学院]
    "校区":
      "北方大区": [北京,天津,郑州,开封,洛阳,平顶山,安阳,鹤壁,新乡,焦作,濮阳,许昌,漯河,三门峡,周口,济源,西安,宝鸡,咸阳,铜川,渭南,延安,榆林,汉中,安康,商洛,北京,朝阳,石家庄,邯郸,邢台,保定,张家口,廊坊,衡水,太原,大同,阳泉,长治,晋城,朔州,吕梁,忻州,晋中,临汾,运城,呼和浩特,包头,乌海,通辽,鄂尔多斯,呼伦贝尔,巴彦淖尔,乌兰察布,兴安盟,锡林郭勒,阿拉善,大连,鞍山,抚顺,本溪,丹东,长春,吉林,四平,辽源,通化,白山,松原,白城,延边,哈尔滨,齐齐哈尔,牡丹江,佳木斯,大庆,绥化,鹤岗,鸡西,黑河,双鸭山,伊春,七台河,大兴安岭,青岛,济宁,日照,济南,淄博,烟台,潍坊,泰安,威海,莱芜,聊城,菏泽,天津,承德,唐山,秦皇岛,沧州,赤峰,沈阳,锦州,营口,阜新,辽阳,盘锦,铁岭,葫芦岛,东营,德州,滨州]
      "中南大区": [长沙,常德,株洲,湘潭,衡阳,岳阳,邵阳,益阳,娄底,怀化,郴州,永州,湘西,张家界,广州,珠海,东莞,中山,佛山,韶关,江门,湛江,茂名,肇庆,梅州,阳江,清远,云浮,三亚,玉林,来宾,崇左,贺州,百色,河池,柳州,桂林,梧州,北海,防城港,钦州,贵港,福州,莆田,三明,泉州,漳州,龙岩,抚州,萍乡,新余,赣州,吉安,宜春,南阳,信阳,武汉,黄石,十堰,宜昌,襄阳,荆州,荆门,鄂州,孝感,黄冈,咸宁,随州,恩施,仙桃,潜江,天门,神农架,驻马店,深圳,汕头,惠州,汕尾,河源,潮州,揭阳,海口,南宁,厦门]
      "华东大区": [杭州,上饶,拉萨,日喀则,山南,林芝,昌都,阿里,那曲,兰州,嘉峪关,金昌,白银,天水,酒泉,张掖,武威,定西,陇南,平凉,庆阳,银川,石嘴山,吴忠,固原,中卫,西宁,海东,海南,海北,黄南,玉树,果洛,海西,台湾,上海,苏州,南通,无锡,蚌埠,淮北,铜陵,安庆,黄山,宿州,池州,淮南,巢湖,阜阳,六安,宣城,亳州,南昌,景德镇,九江,鹰潭,嘉兴,湖州,商丘,南京,镇江,扬州,盐城,徐州,连云港,常州,宿迁,泰州,淮安,合肥,芜湖,马鞍山,滁州,枣庄,临沂,杭州,南平,宁德,宁波,温州,绍兴,金华,衢州,舟山,台州,丽水]
      "西南大区": [泸州,遂宁,内江,宜宾,广安,重庆,成都,绵阳,德阳,自贡,攀枝花,广元,乐山,南充,达州,雅安,眉山,巴中,资阳,阿坝,甘孜,凉山,贵阳,六盘水,遵义,安顺,铜仁,黔西南,毕节,黔东南,黔南,昆明,曲靖,玉溪,保山,昭通,丽江,普洱,临沧,楚雄,红河,文山,西双版纳,大理,德宏,怒江,迪庆,临夏,甘南,乌鲁木齐,克拉玛依,石河子,阿拉尔,图木舒克,五家渠,吐鲁番,哈密,昌吉,博尔塔拉,巴音郭楞,阿克苏,克孜勒,喀什,和田,伊犁,塔城,阿勒泰]
      "位置": [在哪里,地址,在哪]
    "行业词":
      "行业词": [艺术留学,艺术生留学,艺术类留学,艺术出国,艺术类国外读研,艺术类学出国留学,艺术类学生出国留学,艺术出国留学,艺术设计生出国,艺术类专业留学,艺术类出国读研,艺术生出国读研,留学 艺术,艺术 留学,出国留学艺术,设计留学,艺术类 留学,艺术类出国留学,艺术设计类留学,艺术设计留学,艺术生去留学,艺术学留学,艺术设计硕士留学,艺术专业留学,留学艺术,出国留学艺术中介,国外艺术教育机构,留学艺术机构,留学艺术机构排名,留学艺术培训机构,艺术类出国留学机构,艺术设计机构,艺术设计留学机构,艺术生出国留学机构哪个好,艺术生出国留学中介,艺术生出国中介]
    "机构":
      "机构": [机构,中介,中心,集团,公司]
    "海外":
      "海外": [海外,世界,国外,外国,全球]
    "费用":
      "费用": [费用,多少钱,预算,学费,花费,收费,价格,贵不贵,贵吗]
    "申请条件":
      "申请条件": [申请,条件]
    "要求":
      "要求": [要求]
    "竞品词":
      "竞品词": [acg,va,rosso,罗素,斯芬克,sfk,美行思远,维欧,psone,品思,艺盟,美艺,藤门,澳际,新东方,skd,lac,lido,汉艺,aae,krich,野生国际,和创,洛素,爱特,壹思,skf,艺界,一沙,西瑞,af,啄木鸟,指南者,零创,美行远思,AAD国际艺术留学,IAIA艺术留学,欧名艺术留学,东方国际留学,美世,妈妈咪呀,新航道]
    "品牌词":
      "品牌词": [sia]
    "排名":
      "排名": [排名]
      "排行": [排行]
      "排第几": [排第几]
    "疑问":
      "疑问": [好不好,怎么,靠谱吗,哪些,够不够,在哪,好吗,哪个好,好么,如何,哪里好,去哪,哪个]
    "学校/大学":
      "大学": [大学,学院,高校]
      "学校": [学校,院校]
    "学历":
      "本科": [本科]
      "研究生": [研究生]
      "高中": [高中]
    "音乐":
      "音乐": [音乐,钢琴,声乐,伯克利,茱莉亚,柯蒂斯,大提琴,钢琴]
    "作品集":
      "作品集": [作品集]
    "留学词":
      "留学": [留学,出国]
  # 关键词包含其中一种的，直接排除
  keyword-exclude: [武藏野,东京,多摩,女子美术,京都,大阪,爱知县,筑波,长冈,洗足,冲绳,昭和,桐朋,東京,文化服装,杉野,hal,桑沢,成安造型,金泽,日本,赴日,启德,百利天下,psone,威久,坑,黑料,知乎,君行,保利,dtec,dico,rcb,jpa,neo,兰尊,艾末,比末,大洋,独角兽,创艺典,37国际,克瑞斯,lava innovation,顾问,藤门,斯芳克,美型思远,自动定向,美院附中,不建议,移民,书房,筑人,罗马,百度百科,想象,手续,弊端,哦,美元,婚纱,绩点,安吉列,艾斯麦,湖畔,列邦,卡罗国际,诶站lit,bacc国际,博畔,惠禾,诶站lit,瑞玲,康伯思,图卢兹,苏里科夫,大赛官网,山东艺术学院,圣·马丁,西雅图,机械,材料,new art,家长圈,诶站lit,卡罗国际,惠禾,韩中影视,博畔亚洲,ea欧艺,art23国际,汉和明盛,aad艺术,留学狗,uu艺术留学,cp艺术留学,艺术留学cp,fia艺术留学,fau艺术留学,aca艺术留学,abc艺术留学,MA留学,ica艺术留学,upm艺术留学,tiu艺术留学,野生国际,西瑞,品思,lava innovation,艺术高中排名榜,艺术高中,北京艺术学校,千叶大学,九州艺术,南洋理工大学,上海音乐学院,宾州州立大学,hal专门,爱默生学院,高中艺术高校,北京国际艺术学校,北京爱迪国际学校,大师行,大师课,杜克大学,代码,原因,abc 留学艺术,tiu,mcca,aca,art23国际,ea欧艺优设,诶站lit,公共艺术,aplus,一本一诺,baca,aei,夏令营,游学,dfa,瑞茵,驰原,美桥,推荐信,artsking,野生,图片,画图,new art艺术留学,new art,bacc,art23国际艺术留学,cp艺术留学,fau艺术留学,tiu艺术留学,tiu,mcca,loka,弘时,arter,amass,爱多艺,吕芃,文书老师,评价,朱晓辉,优惠,孙胄,市场部,名片,总裁,17s,百科,17l,2016,26万,创始人,管网,挂牌,教务,林涛,事什么,光年,广场,片学校,卡耐基梅隆,yale,卡内基梅隆,漆艺,中专,产品设计网站,就业前景,暑假短期,耶鲁大学,网站大全,牛津大学,进修,欣赏,bbnart,录音,上市,报录,口碑,研究生中心,尤里,诶站lit,bacc,art23,新东方,lido,欧艺优设,读研几年,出国出国,艺术学的,gre,校徽,校友,校长,简称,客座教授,毕业率,榜单,电脑艺术,tisch艺术,作品集模板',作品集有培训,品牌管理类,意义大吗,上大留学,ps留学,cdr作品集画册模板,不需要作品集,是私立,利弊,作品集目录,官方网,学园,MODA,IAAA,FIA,高数,一年招多少人,要读几年,网站首页,体会,到底值不值,几岁,新闻,押金,创意典,双元制,个人申请留学,著名建筑物,案例分析,初步,属于什么行业,金吉列,京华,六所红砖大学,英语要求,学历认证,挂科怎么办,农学院,电影学院奖,会计,商科,不通过中介,法兰西,打版学校,多少钱一个月,服装设计课程,服装设计师,图案素材,服装设计学习班,服装设计需要学,职高,职业学院,服装设计自学,高级服装设计,高端平面设计,画册,哈萨克斯坦,华意通,自己怎么申请出国留学,汉学院,艺术与科技,在职研究生,博士,微留学,室内设计风格,现代室内设计,灵感,神户工科,圣彼得堡国立经济大学,什么是,摄影构图学,草图,山东师范大学,瑞丁大学,日语专业,荣思,前途出国,南美,美思远行,特长生高考政策,名校,低龄,必备清单,英语条件,名牌,欧风,泰晤士,托普仕,万佳留学,折算,文星艺术,新中式,案例,秀丽,匈牙利,马可波罗计划,英吉利,优越留学,实习,古筝,墨西哥,摩洛哥,瑞士,威尼斯]